# Generated by Django 5.1.2 on 2025-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoVolare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='siglas',
            field=models.CharField(default='___', max_length=3),
            preserve_default=False,
        ),
    ]
