# Generated by Django 5.1.2 on 2025-11-04 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id_aerolinea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='logos_aerolineas/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('bandera', models.ImageField(upload_to='banderas_paises/')),
                ('curiosidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos_aeropuertos/')),
                ('aerolineas', models.ManyToManyField(to='appProyectoVolare.aerolinea')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProyectoVolare.pais')),
            ],
        ),
    ]
