# Generated by Django 5.1.3 on 2025-11-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoVolare', '0002_aeropuerto_siglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='pais_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aerolineas_origen', to='appProyectoVolare.pais'),
        ),
    ]
